# Generated by Django 4.0.2 on 2022-03-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='sjects',
            new_name='subject',
        ),
    ]
